In [3]:
import numpy as np

In [4]:
myPythonList = [1,3,5,7,9]
print(myPythonList)

#### prints the list

[1, 3, 5, 7, 9]


In [5]:
numpy_array_from_list = np.array(myPythonList)
numpy_array_from_list

#### makes array from list

array([1, 3, 5, 7, 9])

In [6]:
a = np.array([1,3,5,7,9])
print(a)

#### prints array

[1 3 5 7 9]


In [7]:
x = numpy_array_from_list + 10
print(x)

#### adds 10 to array and prints

[11 13 15 17 19]


In [9]:
b = np.array([1,2,3])
print(b.shape)
print(b.dtype)

#### gives shape that is the number of rows and columns
#### also gives the datatype of the values inside the array

(3,)
int32


In [10]:
c = np.array([1,2,3.0,4.56,5])
print(c.dtype)

#### gives out datatype of the value inside the array

float64


In [11]:
d = np.array([(1,2,3),
                (4,5,6)])
print(d)

#### an array in 2 dimension

[[1 2 3]
 [4 5 6]]


In [13]:
e = np.array([
    [[1, 2,3],
        [4, 5, 6]],
    [[7, 8,9],
        [10, 11, 12]]
])
print(e.shape)
(2, 2, 3)
print(e)

#### an array in 3 dimension

(2, 2, 3)
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [14]:
import numpy as np
x = np.zeros((2,2), dtype = np.int16)
print(x)

#### zero matrix of size 2x2

[[0 0]
 [0 0]]


In [15]:
import numpy as np
y= np.ones((1,2,3), dtype=np.int16)
print(y.shape)
print(y)

#### gives the shape of matrix and gives out a ones matrix of the size corresponding to the shape of y

(1, 2, 3)
[[[1 1 1]
  [1 1 1]]]


In [16]:
import numpy as np
e = np.array([(1,2,3), (4,5,6)])
print(e)
e.reshape(3,2)

#### to reshaping the data to our convenience

[[1 2 3]
 [4 5 6]]


array([[1, 2],
       [3, 4],
       [5, 6]])

In [17]:
e.flatten()

#### gives out all the data in a single line

array([1, 2, 3, 4, 5, 6])

In [18]:
import numpy as np
f = np.array([4,5,6])
g = np.array([7,8,9])

print('Horizontal Append:', np.hstack((f, g)))

#### displays data of both f and g horizontally using hstack

Horizontal Append: [4 5 6 7 8 9]


In [19]:
import numpy as np
f = np.array([1,3,5])
g = np.array([2,4,6])

print('Vertical Append:', np.vstack((f,g)))

#### displays data of both f and g vertically using vstack

Vertical Append: [[1 3 5]
 [2 4 6]]


In [20]:
normal_array = np.random.normal(5, 0.5, 10)
print(normal_array)

#### generates random numbers by specifying the mean the deviation and number of returns

[4.38350382 4.60919453 4.27684004 4.8072866  4.96327016 5.34605245
 4.76171815 5.84830545 5.35251341 4.6115976 ]


In [21]:
A = np.matrix(np.ones((4,4)))
print(A)

#### ones matrix of size 4x4

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [22]:
np.asarray(A)[2]=2
print(A)

#### prints input as an array

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [1. 1. 1. 1.]]


In [23]:
np.arange(1, 11)

#### arranges numbers from 1 to 11

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
np.arange(1, 20, 0.8)

#### arranges numbers from 1 to 20 with 0.8 as the deviation between two consecutive numbers

array([ 1. ,  1.8,  2.6,  3.4,  4.2,  5. ,  5.8,  6.6,  7.4,  8.2,  9. ,
        9.8, 10.6, 11.4, 12.2, 13. , 13.8, 14.6, 15.4, 16.2, 17. , 17.8,
       18.6, 19.4])

In [25]:
import numpy as np
np.linspace(0.5, 21.7, num=17)

#### gives out evencly spaced output between the numbers

array([ 0.5  ,  1.825,  3.15 ,  4.475,  5.8  ,  7.125,  8.45 ,  9.775,
       11.1  , 12.425, 13.75 , 15.075, 16.4  , 17.725, 19.05 , 20.375,
       21.7  ])

In [26]:
np.linspace(0.0, 20.0, num=20, endpoint=False)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19.])

In [28]:
np.logspace(100.0, 200.0, num=50)

#### similar to linspace but gives out log values of input numbers

array([1.00000000e+100, 1.09854114e+102, 1.20679264e+104, 1.32571137e+106,
       1.45634848e+108, 1.59985872e+110, 1.75751062e+112, 1.93069773e+114,
       2.12095089e+116, 2.32995181e+118, 2.55954792e+120, 2.81176870e+122,
       3.08884360e+124, 3.39322177e+126, 3.72759372e+128, 4.09491506e+130,
       4.49843267e+132, 4.94171336e+134, 5.42867544e+136, 5.96362332e+138,
       6.55128557e+140, 7.19685673e+142, 7.90604321e+144, 8.68511374e+146,
       9.54095476e+148, 1.04811313e+151, 1.15139540e+153, 1.26485522e+155,
       1.38949549e+157, 1.52641797e+159, 1.67683294e+161, 1.84206997e+163,
       2.02358965e+165, 2.22299648e+167, 2.44205309e+169, 2.68269580e+171,
       2.94705170e+173, 3.23745754e+175, 3.55648031e+177, 3.90693994e+179,
       4.29193426e+181, 4.71486636e+183, 5.17947468e+185, 5.68986603e+187,
       6.25055193e+189, 6.86648845e+191, 7.54312006e+193, 8.28642773e+195,
       9.10298178e+197, 1.00000000e+200])

In [29]:
x = np.array([1,2,3], dtype=np.complex128)
x.itemsize	

16

In [30]:
import numpy as np
e  = np.array([(1,2,3), (3,2,1)])
print(e)

#### slices data

[[1 2 3]
 [3 2 1]]


In [31]:
print('First Row:', e[0])
print('Second Row:', e[1])

#### first and second column

First Row: [1 2 3]
Second Row: [3 2 1]


In [32]:
print('Second Column:', e[:,1])

#### prints out second column

Second Column: [2 2]


In [33]:
print(e[1, :2])

#### 2 values of second row

[3 2]


In [34]:
print(e[:2,1])

#### 2 values of second column

[2 2]


In [35]:
import numpy as np
normal_array = np.random.normal(1, 0.5, 10)
print(normal_array)	

#### normal is given as output

[1.08415199 1.28521345 1.82472859 0.84017108 1.09951091 1.73521992
 0.73298946 0.7433513  1.55926832 1.52891449]


In [36]:
print(np.min(normal_array))
print(np.max(normal_array))
print(np.mean(normal_array))
print(np.median(normal_array))
print(np.std(normal_array))

#### prints out min max mean median and std

0.7329894598045319
1.8247285880117947
1.243351950750342
1.1923621786282776
0.38497981902897427


In [39]:
a = np.array([1,2,3])
b = np.array([3,2,1])

np.dot(a, b)

#### dot product

10

In [41]:
p = [[1,2],[3,4]]
q = [[5,6],[6,5]]

np.matmul(p, q)

#### gives out matrix multiplication value

array([[17, 16],
       [39, 38]])

In [42]:
A = np.array([[6, 1, 1],
                [4, -2, 5],
                [2, 8, 7]])

print(np.linalg.inv(A))

#### inversing a matrix

[[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]


In [43]:
nArray = np.array([[50, 29], [30, 44]])

print("Numpy Matrix is:")
print(nArray)

det = np.linalg.det(nArray)

print("\nDeterminant of given 2X2 matrix is:")
print(int(det))

#### determinant of a matrix

Numpy Matrix is:
[[50 29]
 [30 44]]

Determinant of given 2X2 matrix is:
1330


In [44]:
x = np.array([[1,1,1], [0,1,2], [1,5,3]])

np.linalg.matrix_rank(x)

#### matrix rank

3

In [45]:
ex_matrix = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12],
    [13,14,15,16]
])
eigenvalues, eigenvectors = np.linalg.eig(ex_matrix)
print(eigenvalues, eigenvectors)

#### to get eigenvalues and eigen vectors

[ 3.62093727e+01 -2.20937271e+00 -3.18863232e-15 -1.34840081e-16] [[-0.15115432  0.72704996  0.50370019 -0.06456091]
 [-0.34923733  0.28320876 -0.8319577  -0.31932112]
 [-0.54732033 -0.16063243  0.15281481  0.83232496]
 [-0.74540333 -0.60447363  0.17544269 -0.44844294]]


In [46]:
d = np.matrix('[6, 2; 3, 4]')

diag = d.diagonal()

print(diag)

#### gives diagonal elements

[[6 4]]


In [47]:
t = np.matrix('[1, 2; 5, 10]')

trans = t.transpose()
 
print(trans)

#### transpose of a matrix

[[ 1  5]
 [ 2 10]]


In [48]:
tr = np.matrix('[3, 4; 12, 13]')

tracem = tr.trace()

print(tracem)

#### trace of a matrix

[[16]]
